"""Render all sections successfully before writing a document."""

import re
from dataclasses import dataclass
from pathlib import PurePath

from agent_smith.application.ports import (
    CommandRunner,
    DocumentWriter,
    GenerationError,
    GenerationRequest,
    OverviewParser,
    OverviewSection,
    TextReader,
)


def content_lines(content: str) -> str:
    """Normalize line endings and remove only surrounding blank lines."""
    lines = content.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def inline_code(value: str) -> str:
    """Keep literal backticks and edge spaces inside a Markdown code span."""
    fence = "`" * (max((len(run) for run in re.findall(r"`+", value)), default=0) + 1)
    padding = " " if value.startswith(("`", " ")) or value.endswith(("`", " ")) else ""
    return f"{fence}{padding}{value}{padding}{fence}"


def heading(value: str) -> str:
    """Escape Markdown punctuation so the configured title stays one heading."""
    return "".join("\\" + char if char in "\\`*_[]<>#" else char for char in value)


@dataclass
class GenerationService:
    reader: TextReader
    overview: OverviewParser
    commands: CommandRunner
    writer: DocumentWriter

    def generate(self, request: GenerationRequest) -> None:
        """Generate one deterministic document via injected effect boundaries."""
        if not request.output.strip() or "\n" in request.output or "\r" in request.output:
            raise GenerationError("The output path must be nonempty and on one line.")
        if not request.sections:
            raise GenerationError("No sections enabled; enable overview or configure a section.")
        for section in request.sections:
            if not section.title.strip() or any(c in section.title for c in "\r\n"):
                raise GenerationError("Section titles must be nonempty and on one line.")
        parts = [f"# {heading(PurePath(request.output).name)}"]
        for section in request.sections:
            if isinstance(section, OverviewSection):
                body = self.overview.extract(self.reader.read(section.source))
                command = request.command
            else:
                if not section.command.strip() or any(c in section.command for c in "\r\n"):
                    raise GenerationError("Section commands must be nonempty and on one line.")
                body = self.commands.run(section.command)
                command = section.command
            provenance = (
                "*This section was automatically generated by executing the command: "
                f"**{inline_code(command)}**.*"
            )
            body = content_lines(body)
            if not body:
                raise GenerationError(f"Section {section.title!r} produced no content.")
            parts.append(f"## {heading(section.title)}\n\n{body}\n\n> {provenance}")
        self.writer.write(request.output, "\n\n".join(parts) + "\n")
