"""A small set of complete user journeys through the installed package."""

import json
import subprocess
import sys
from pathlib import Path


def invoke(directory: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-I", "-m", "agent_smith", *arguments],
        cwd=directory,
        capture_output=True,
        text=True,
        timeout=10,
    )


def test_default_generation_is_repeatable(tmp_path: Path) -> None:
    # Given the README convention in a project outside the checkout.
    (tmp_path / "README.md").write_text(
        "# Demo\n\nA **useful** project.\n\n## Install\nIgnored.\n", encoding="utf-8"
    )
    # When the installed CLI generates the same document twice.
    first = invoke(tmp_path)
    first_bytes = (tmp_path / "AGENTS.md").read_bytes()
    second = invoke(tmp_path)
    # Then output is byte-identical, contains only the overview and has provenance.
    assert first.returncode == second.returncode == 0
    assert first.stdout == first.stderr == second.stdout == second.stderr == ""
    assert first_bytes == (tmp_path / "AGENTS.md").read_bytes()
    assert first_bytes == (
        b"# AGENTS.md\n\n## Overview\n\nA **useful** project.\n\n"
        b"> *This section was automatically generated by executing the command: "
        b"**`agent-smith`**.*\n"
    )


def test_custom_extractor_replaces_builtin_with_cli_overrides(tmp_path: Path) -> None:
    # Given a custom extractor configuration and no README.
    command = f'''"{sys.executable}" -c "print('Custom content.')"'''
    (tmp_path / "custom.toml").write_text(
        'output = "config.md"\n[[sections]]\ntitle = "My overview"\ncommand = '
        + json.dumps(command)
        + "\n",
        encoding="utf-8",
    )
    # When the user disables the built-in and overrides the output path.
    result = invoke(tmp_path, "--config", "custom.toml", "--no-overview", "--output", "notes.md")
    # Then the custom command supplies the section and its exact provenance.
    assert result.returncode == 0, result.stderr
    document = (tmp_path / "notes.md").read_text(encoding="utf-8")
    assert "# notes.md\n\n## My overview\n\nCustom content." in document
    assert f"command: **`{command}`**" in document
    assert not (tmp_path / "config.md").exists()


def test_failing_extractor_preserves_existing_document(tmp_path: Path) -> None:
    # Given a failing custom command and an existing instruction file.
    command = f'''"{sys.executable}" -c "import sys; sys.exit(7)"'''
    (tmp_path / "agent-smith.toml").write_text(
        '[overview]\nenabled = false\n[[sections]]\ntitle = "Custom"\ncommand = '
        + json.dumps(command)
        + "\n",
        encoding="utf-8",
    )
    output = tmp_path / "AGENTS.md"
    output.write_bytes(b"Existing document\n")
    # When generation fails.
    result = invoke(tmp_path)
    # Then no partial output replaces the existing document.
    assert result.returncode == 1
    assert "exit 7" in result.stderr
    assert result.stdout == ""
    assert output.read_bytes() == b"Existing document\n"


def test_missing_readme_reports_failure_without_output(tmp_path: Path) -> None:
    # Given an empty project directory.
    output = tmp_path / "AGENTS.md"
    # When convention-based generation is attempted.
    result = invoke(tmp_path)
    # Then the diagnostic names the missing input and no output is created.
    assert result.returncode == 1
    assert "README.md" in result.stderr
    assert not output.exists()


def test_just_help_generates_grouped_commands_without_running_them(tmp_path: Path) -> None:
    # Given a real justfile whose documented recipe would create a sentinel if executed.
    (tmp_path / "README.md").write_text("# Demo\n\nOverview.\n")
    (tmp_path / "justfile").write_text(
        '# List commands.\n[group("Help")]\nhelp:\n    @just --list\n\n'
        '# Build the project.\n[group("Build")]\nbuild target="wheel":\n'
        "    @touch should-not-exist\n"
    )
    # When the installed CLI generates the document twice from the real help command.
    first = invoke(tmp_path)
    output = tmp_path / "AGENTS.md"
    content = output.read_bytes()
    second = invoke(tmp_path)
    # Then grouped command signatures and provenance are deterministic and recipes did not run.
    assert first.returncode == second.returncode == 0, first.stderr + second.stderr
    assert content == output.read_bytes()
    assert b'## Available commands\n\n### Build\n\n- `just build target="wheel"`' in content
    assert b"### Help\n\n- `just help`" in content
    assert b"**`just help`**" in content
    assert not (tmp_path / "should-not-exist").exists()


def test_disabling_available_commands_avoids_executing_help(tmp_path: Path) -> None:
    # Given a project with a failing help recipe.
    (tmp_path / "README.md").write_text("# Demo\n\nOverview.\n")
    (tmp_path / "justfile").write_text("help:\n    @exit 9\n")
    # When the built-in is explicitly disabled from the CLI.
    result = invoke(tmp_path, "--no-available-commands")
    # Then generation succeeds without an available-commands section.
    assert result.returncode == 0, result.stderr
    assert "## Available commands" not in (tmp_path / "AGENTS.md").read_text()


def test_invalid_help_preserves_existing_document(tmp_path: Path) -> None:
    # Given a help recipe producing unsupported output and an existing document.
    (tmp_path / "README.md").write_text("# Demo\n\nOverview.\n")
    (tmp_path / "justfile").write_text("help:\n    @echo 'Not a recipe list'\n")
    output = tmp_path / "AGENTS.md"
    output.write_text("Previous instructions\n")
    # When the CLI cannot interpret the help output.
    result = invoke(tmp_path)
    # Then the error is actionable and the previous document remains intact.
    assert result.returncode == 1
    assert "just --list" in result.stderr
    assert output.read_text() == "Previous instructions\n"


def test_mise_tech_stack_generation_is_repeatable(tmp_path: Path) -> None:
    # Given declared versions, an install hook and environment data in a root mise file.
    (tmp_path / "README.md").write_text("# Demo\n\nOverview.\n")
    (tmp_path / "mise.toml").write_text(
        '[tools]\npython=["3.14", "3.10"]\n'
        'uv={version="latest", postinstall="touch should-not-exist"}\n'
        '[env]\nPRIVATE_VALUE="not-in-output"\n'
    )
    # When the installed CLI generates twice without invoking mise.
    first = invoke(tmp_path)
    output = tmp_path / "AGENTS.md"
    content = output.read_bytes()
    second = invoke(tmp_path)
    # Then the result is deterministic and contains only declared tool data.
    assert first.returncode == second.returncode == 0, first.stderr + second.stderr
    assert content == output.read_bytes()
    assert (
        "## Main tech stack\n\n- `python` — `3.14`, `3.10`\n- `uv` — `latest`" in content.decode()
    )
    assert b"not-in-output" not in content
    assert not (tmp_path / "should-not-exist").exists()


def test_malformed_mise_fails_safely_and_can_be_disabled(tmp_path: Path) -> None:
    # Given a malformed mise file and a previous generated document.
    (tmp_path / "README.md").write_text("# Demo\n\nOverview.\n")
    (tmp_path / "mise.toml").write_text("[broken")
    output = tmp_path / "AGENTS.md"
    output.write_text("Previous instructions\n")
    # When default generation encounters the invalid input.
    failed = invoke(tmp_path)
    previous = output.read_text()
    disabled = invoke(tmp_path, "--no-tech-stack")
    # Then failure preserves the file and disabling the extractor restores generation.
    assert failed.returncode == 1
    assert "mise.toml" in failed.stderr
    assert previous == "Previous instructions\n"
    assert disabled.returncode == 0, disabled.stderr
    assert "## Main tech stack" not in output.read_text()
