"""A small set of complete user journeys through the installed package."""

import json
import subprocess
import sys
from pathlib import Path


def invoke(directory: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-I", "-m", "agent_smith", *arguments],
        cwd=directory,
        capture_output=True,
        text=True,
        timeout=10,
    )


def test_default_generation_is_repeatable(tmp_path: Path) -> None:
    # Given the README convention in a project outside the checkout.
    (tmp_path / "README.md").write_text(
        "# Demo\n\nA **useful** project.\n\n## Install\nIgnored.\n", encoding="utf-8"
    )
    # When the installed CLI generates the same document twice.
    first = invoke(tmp_path)
    first_bytes = (tmp_path / "AGENTS.md").read_bytes()
    second = invoke(tmp_path)
    # Then output is byte-identical, contains only the overview and has provenance.
    assert first.returncode == second.returncode == 0
    assert first.stdout == first.stderr == second.stdout == second.stderr == ""
    assert first_bytes == (tmp_path / "AGENTS.md").read_bytes()
    assert first_bytes == (
        b"# AGENTS.md\n\n## Overview\n\nA **useful** project.\n\n"
        b"> *This section was automatically generated by executing the command: "
        b"**`agent-smith`**.*\n"
    )


def test_custom_extractor_replaces_builtin_with_cli_overrides(tmp_path: Path) -> None:
    # Given a custom extractor configuration and no README.
    command = f'''"{sys.executable}" -c "print('Custom content.')"'''
    (tmp_path / "custom.toml").write_text(
        'output = "config.md"\n[[sections]]\ntitle = "My overview"\ncommand = '
        + json.dumps(command)
        + "\n",
        encoding="utf-8",
    )
    # When the user disables the built-in and overrides the output path.
    result = invoke(tmp_path, "--config", "custom.toml", "--no-overview", "--output", "notes.md")
    # Then the custom command supplies the section and its exact provenance.
    assert result.returncode == 0, result.stderr
    document = (tmp_path / "notes.md").read_text(encoding="utf-8")
    assert "# notes.md\n\n## My overview\n\nCustom content." in document
    assert f"command: **`{command}`**" in document
    assert not (tmp_path / "config.md").exists()


def test_failing_extractor_preserves_existing_document(tmp_path: Path) -> None:
    # Given a failing custom command and an existing instruction file.
    command = f'''"{sys.executable}" -c "import sys; sys.exit(7)"'''
    (tmp_path / "agent-smith.toml").write_text(
        '[overview]\nenabled = false\n[[sections]]\ntitle = "Custom"\ncommand = '
        + json.dumps(command)
        + "\n",
        encoding="utf-8",
    )
    output = tmp_path / "AGENTS.md"
    output.write_bytes(b"Existing document\n")
    # When generation fails.
    result = invoke(tmp_path)
    # Then no partial output replaces the existing document.
    assert result.returncode == 1
    assert "exit 7" in result.stderr
    assert result.stdout == ""
    assert output.read_bytes() == b"Existing document\n"


def test_missing_readme_reports_failure_without_output(tmp_path: Path) -> None:
    # Given an empty project directory.
    output = tmp_path / "AGENTS.md"
    # When convention-based generation is attempted.
    result = invoke(tmp_path)
    # Then the diagnostic names the missing input and no output is created.
    assert result.returncode == 1
    assert "README.md" in result.stderr
    assert not output.exists()
