"""Application behavior is independent of files, shells and CLI libraries."""

from dataclasses import dataclass, field

import pytest

from agent_smith.adapters.adr import AdrListParser
from agent_smith.application.generation import (
    GenerationService,
    content_lines,
    heading,
    inline_code,
)
from agent_smith.application.ports import (
    CommandSection,
    GenerationError,
    GenerationRequest,
    OverviewSection,
)


@dataclass
class Ports:
    files: dict[str, str] = field(default_factory=lambda: {"README.md": "source"})
    commands: list[str] = field(default_factory=list)
    failure: bool = False

    def read(self, path: str) -> str:
        return self.files[path]

    def extract(self, markdown: str) -> str:
        assert markdown == "source"
        return "Intro."

    def run(self, command: str) -> str:
        self.commands.append(command)
        if self.failure:
            raise GenerationError("command failed")
        return "Custom.\r\n"

    def render(self, output: str) -> str:
        return "- `just check` — Check the repository."

    def write(self, path: str, content: str) -> None:
        self.files[path] = content


def test_generation_renders_order_and_exact_provenance() -> None:
    # Given a built-in section followed by a custom command and in-memory ports.
    ports = Ports()
    request = GenerationRequest(
        "notes.md",
        (OverviewSection(), CommandSection("Tools", "./tools.sh --all")),
        command="agent-smith --config project.toml --output notes.md",
    )
    # When the application generates the document.
    GenerationService(ports, ports, ports, ports, ports, ports, AdrListParser()).generate(request)
    # Then the deterministic document preserves section order and command spelling.
    assert ports.commands == ["./tools.sh --all"]
    assert ports.files["notes.md"] == (
        "# notes.md\n\n## Overview\n\nIntro.\n\n"
        "> *This section was automatically generated by executing the command: "
        "**`agent-smith --config project.toml --output notes.md`**.*\n\n"
        "## Tools\n\nCustom.\n\n"
        "> *This section was automatically generated by executing the command: "
        "**`./tools.sh --all`**.*\n"
    )


def test_section_titles_may_contain_any_letter() -> None:
    # Given a section whose title happens to contain the letter X.
    ports = Ports()
    request = GenerationRequest(sections=(CommandSection("X", "echo ok"),))
    # When the document is generated.
    GenerationService(ports, ports, ports, ports, ports, ports, AdrListParser()).generate(request)
    # Then the ordinary letter is accepted in the title.
    assert "## X" in ports.files["AGENTS.md"]


def test_failure_preserves_existing_document() -> None:
    # Given an existing output and a custom command that fails after overview extraction.
    ports = Ports(failure=True)
    ports.files["AGENTS.md"] = "Existing document"
    request = GenerationRequest(sections=(OverviewSection(), CommandSection("Tools", "failing")))
    # When one section cannot be generated.
    with pytest.raises(GenerationError):
        GenerationService(ports, ports, ports, ports, ports, ports, AdrListParser()).generate(
            request
        )
    # Then no partial output is written.
    assert ports.files["AGENTS.md"] == "Existing document"


@pytest.mark.parametrize(
    ("generation_request", "message"),
    [
        (GenerationRequest(output=""), "The output path must be nonempty and on one line."),
        (
            GenerationRequest(output="bad\nname"),
            "The output path must be nonempty and on one line.",
        ),
        (
            GenerationRequest(output="bad\rname"),
            "The output path must be nonempty and on one line.",
        ),
        (
            GenerationRequest(sections=()),
            "No sections enabled; enable overview or configure a section.",
        ),
        (
            GenerationRequest(sections=(CommandSection("", "ok"),)),
            "Section titles must be nonempty and on one line.",
        ),
        (
            GenerationRequest(sections=(CommandSection("bad\ntitle", "ok"),)),
            "Section titles must be nonempty and on one line.",
        ),
        (
            GenerationRequest(sections=(CommandSection("bad\rtitle", "ok"),)),
            "Section titles must be nonempty and on one line.",
        ),
        (
            GenerationRequest(sections=(CommandSection("Title", ""),)),
            "Section commands must be nonempty and on one line.",
        ),
        (
            GenerationRequest(sections=(CommandSection("Title", "bad\ncommand"),)),
            "Section commands must be nonempty and on one line.",
        ),
    ],
)
def test_invalid_requests_do_not_write(generation_request: GenerationRequest, message: str) -> None:
    # Given an invalid generation request and fresh in-memory ports.
    ports = Ports()
    # When the request is validated.
    with pytest.raises(GenerationError) as failure:
        GenerationService(ports, ports, ports, ports, ports, ports, AdrListParser()).generate(
            generation_request
        )
    # Then the failure is actionable and the output is not created.
    assert str(failure.value) == message
    assert "AGENTS.md" not in ports.files


@pytest.mark.parametrize(
    ("source", "expected"),
    [
        ("\r\n  code  \r\n", "  code  "),
        ("\n\n", ""),
        ("A\n\nB\n", "A\n\nB"),
        ("A\r\n\r\nB\r\n", "A\n\nB"),
        ("A\rB", "A\nB"),
    ],
)
def test_content_normalization_preserves_meaning(source: str, expected: str) -> None:
    # Given content with line endings and meaningful internal whitespace.
    content = source
    # When it is normalized for deterministic output.
    result = content_lines(content)
    # Then only outer blank lines and line endings change.
    assert result == expected


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ("echo hi", "`echo hi`"),
        ("echo `date`", "`` echo `date` ``"),
        ("`value`", "`` `value` ``"),
        (" hi ", "`  hi  `"),
        ("`x", "`` `x ``"),
        ("x ", "` x  `"),
        (" x", "`  x `"),
    ],
)
def test_provenance_quotes_literal_commands(value: str, expected: str) -> None:
    # Given a command that may itself contain Markdown code delimiters.
    command = value
    # When the provenance code span is constructed.
    result = inline_code(command)
    # Then delimiters preserve the literal command.
    assert result == expected


def test_heading_escapes_markdown_syntax() -> None:
    # Given a title containing formatting, links and an ordinary capital X.
    title = "[Overview](url) *bold* X"
    # When the title is rendered as plain heading text.
    result = heading(title)
    # Then Markdown syntax is escaped while ordinary text is retained.
    assert result == "\\[Overview\\](url) \\*bold\\* X"


def test_available_commands_uses_injected_parser_and_exact_provenance() -> None:
    # Given a help command and explicitly injected ports.
    from agent_smith.application.ports import AvailableCommandsSection

    ports = Ports()
    request = GenerationRequest(sections=(AvailableCommandsSection(command="just --list"),))
    # When the section is rendered through the help parser.
    GenerationService(ports, ports, ports, ports, ports, ports, AdrListParser()).generate(request)
    # Then interpreted Markdown and the executed command appear in the generated document.
    assert ports.commands == ["just --list"]
    assert (
        "## Available commands\n\n- `just check` — Check the repository."
        in ports.files["AGENTS.md"]
    )
    assert "**`just --list`**" in ports.files["AGENTS.md"]


def test_tech_stack_reads_source_without_executing_a_command() -> None:
    # Given the real pure parser and an in-memory filesystem boundary.
    from agent_smith.adapters.mise import MiseTechStackParser
    from agent_smith.application.ports import TechStackSection

    ports = Ports(files={"tools.toml": '[tools]\npython = "3.14"'})
    request = GenerationRequest(
        sections=(TechStackSection("Stack", "tools.toml"),),
        command="agent-smith --config custom.toml",
    )
    # When generation interprets the source through its injected parser.
    GenerationService(
        ports, ports, ports, ports, ports, MiseTechStackParser(), AdrListParser()
    ).generate(request)
    # Then the section lists declared tools and the actual invocation, with no subprocess.
    assert "## Stack\n\n- `python` — `3.14`" in ports.files["AGENTS.md"]
    assert "**`agent-smith --config custom.toml`**" in ports.files["AGENTS.md"]
    assert ports.commands == []


def test_invalid_tech_stack_preserves_output_and_identifies_source() -> None:
    # Given an invalid mise file and an existing document behind injected boundaries.
    from agent_smith.adapters.mise import MiseTechStackParser
    from agent_smith.application.ports import TechStackSection

    ports = Ports(files={"tools.toml": "[broken", "AGENTS.md": "Previous document"})
    request = GenerationRequest(sections=(TechStackSection(source="tools.toml"),))
    # When generation fails to parse the selected source.
    with pytest.raises(GenerationError, match=r"tools\.toml"):
        GenerationService(
            ports, ports, ports, ports, ports, MiseTechStackParser(), AdrListParser()
        ).generate(request)
    # Then the original output is preserved.
    assert ports.files["AGENTS.md"] == "Previous document"


@dataclass
class AdrPorts(Ports):
    listing: str = "docs/adr/0001-use-python.md\n"

    def run(self, command: str) -> str:
        self.commands.append(command)
        return self.listing


def test_architecture_decisions_uses_adr_list_without_reading_decisions() -> None:
    # Given only .adr-dir as readable input and the real parser behind the port.
    from agent_smith.application.ports import ArchitectureDecisionsSection

    ports = AdrPorts(files={".adr-dir": "docs/adr\n"})
    request = GenerationRequest(sections=(ArchitectureDecisionsSection(),))
    # When the built-in generates a section.
    GenerationService(ports, ports, ports, ports, ports, ports, AdrListParser()).generate(request)
    # Then it calls adr list and emits its provenance without opening an ADR file.
    assert ports.commands == ["adr list"]
    assert ports.files["AGENTS.md"] == (
        "# AGENTS.md\n\n## Architecture decisions\n\nDirectory: `docs/adr`\n\n"
        "- `0001-use-python`\n\n"
        "> *This section was automatically generated by executing the command: **`adr list`**.*\n"
    )


def test_invalid_adr_listing_preserves_previous_output() -> None:
    # Given a listing inconsistent with the declared directory.
    from agent_smith.application.ports import ArchitectureDecisionsSection

    ports = AdrPorts(files={".adr-dir": "docs/adr", "AGENTS.md": "Previous"}, listing="Unexpected")
    # When the real parser rejects the command output.
    with pytest.raises(GenerationError, match="adr list"):
        GenerationService(ports, ports, ports, ports, ports, ports, AdrListParser()).generate(
            GenerationRequest(sections=(ArchitectureDecisionsSection(),))
        )
    # Then no partial document was written.
    assert ports.files["AGENTS.md"] == "Previous"
