"""Application behavior is independent of files, shells and CLI libraries."""

from dataclasses import dataclass, field

import pytest

from agent_smith.application.generation import (
    GenerationService,
    content_lines,
    heading,
    inline_code,
)
from agent_smith.application.ports import (
    CommandSection,
    GenerationError,
    GenerationRequest,
    OverviewSection,
)


@dataclass
class Ports:
    files: dict[str, str] = field(default_factory=lambda: {"README.md": "source"})
    commands: list[str] = field(default_factory=list)
    failure: bool = False

    def read(self, path: str) -> str:
        return self.files[path]

    def extract(self, markdown: str) -> str:
        assert markdown == "source"
        return "Intro."

    def run(self, command: str) -> str:
        self.commands.append(command)
        if self.failure:
            raise GenerationError("command failed")
        return "Custom.\r\n"

    def write(self, path: str, content: str) -> None:
        self.files[path] = content


def test_generation_renders_order_and_exact_provenance() -> None:
    # Given a built-in section followed by a custom command and in-memory ports.
    ports = Ports()
    request = GenerationRequest(
        "notes.md",
        (OverviewSection(), CommandSection("Tools", "./tools.sh --all")),
        command="agent-smith --config project.toml --output notes.md",
    )
    # When the application generates the document.
    GenerationService(ports, ports, ports, ports).generate(request)
    # Then the deterministic document preserves section order and command spelling.
    assert ports.commands == ["./tools.sh --all"]
    assert ports.files["notes.md"] == (
        "# notes.md\n\n## Overview\n\nIntro.\n\n"
        "> *This section was automatically generated by executing the command: "
        "**`agent-smith --config project.toml --output notes.md`**.*\n\n"
        "## Tools\n\nCustom.\n\n"
        "> *This section was automatically generated by executing the command: "
        "**`./tools.sh --all`**.*\n"
    )


def test_failure_preserves_existing_document() -> None:
    # Given an existing output and a custom command that fails after overview extraction.
    ports = Ports(failure=True)
    ports.files["AGENTS.md"] = "Existing document"
    request = GenerationRequest(sections=(OverviewSection(), CommandSection("Tools", "failing")))
    # When one section cannot be generated.
    with pytest.raises(GenerationError):
        GenerationService(ports, ports, ports, ports).generate(request)
    # Then no partial output is written.
    assert ports.files["AGENTS.md"] == "Existing document"


@pytest.mark.parametrize(
    "generation_request",
    [
        GenerationRequest(output=""),
        GenerationRequest(output="bad\nname"),
        GenerationRequest(sections=()),
        GenerationRequest(sections=(CommandSection("", "ok"),)),
        GenerationRequest(sections=(CommandSection("bad\ntitle", "ok"),)),
        GenerationRequest(sections=(CommandSection("Title", ""),)),
        GenerationRequest(sections=(CommandSection("Title", "bad\ncommand"),)),
    ],
)
def test_invalid_requests_do_not_write(generation_request: GenerationRequest) -> None:
    # Given an invalid generation request and fresh in-memory ports.
    ports = Ports()
    # When the request is validated.
    with pytest.raises(GenerationError):
        GenerationService(ports, ports, ports, ports).generate(generation_request)
    # Then the output is not created.
    assert "AGENTS.md" not in ports.files


@pytest.mark.parametrize(
    ("source", "expected"), [("\r\n  code  \r\n", "  code  "), ("\n\n", ""), ("A\n\nB\n", "A\n\nB")]
)
def test_content_normalization_preserves_meaning(source: str, expected: str) -> None:
    # Given content with line endings and meaningful internal whitespace.
    content = source
    # When it is normalized for deterministic output.
    result = content_lines(content)
    # Then only outer blank lines and line endings change.
    assert result == expected


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ("echo hi", "`echo hi`"),
        ("echo `date`", "`` echo `date` ``"),
        ("`value`", "`` `value` ``"),
        (" hi ", "`  hi  `"),
    ],
)
def test_provenance_quotes_literal_commands(value: str, expected: str) -> None:
    # Given a command that may itself contain Markdown code delimiters.
    command = value
    # When the provenance code span is constructed.
    result = inline_code(command)
    # Then delimiters preserve the literal command.
    assert result == expected


def test_heading_escapes_markdown_syntax() -> None:
    # Given a title containing formatting and links.
    title = "[Overview](url) *bold*"
    # When the title is rendered as plain heading text.
    result = heading(title)
    # Then Markdown syntax is escaped while ordinary text is retained.
    assert result == "\\[Overview\\](url) \\*bold\\*"
